/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface File {
  'id' : string,
  'isEncrypted' : boolean,
  'fileLink' : [] | [string],
  'fileType' : FileType,
}
export type FileType = { 'mp4' : null } |
  { 'pdf' : null } |
  { 'clarifiedPdf' : null } |
  { 'jpeg' : null } |
  { 'answeredQueries' : null } |
  { 'shortVideo' : null } |
  { 'notes' : null } |
  { 'longVideo' : null } |
  { 'mp3Audio' : null } |
  { 'pdfEncrypted' : null } |
  { 'zoomChart' : null } |
  { 'screenshot' : null } |
  { 'pdfWithQRCode' : null };
export interface Lesson {
  'id' : string,
  'files' : Array<File>,
  'startTime' : bigint,
  'title' : string,
  'endTime' : bigint,
  'description' : string,
  'teacherName' : string,
  'videoLink' : [] | [string],
  'periodicReminders' : Reminders,
  'rating' : number,
  'ratingsCount' : bigint,
  'teacherSchedule' : Array<TeacherSchedule>,
}
export interface LessonReminder {
  'interval' : bigint,
  'text' : string,
  'isActive' : boolean,
}
export type LessonStatus = { 'notStarted' : null } |
  { 'started' : null } |
  { 'completed' : null } |
  { 'paused' : null };
export interface LessonStatusUpdate {
  'lessonId' : string,
  'newStatus' : LessonStatus,
}
export interface Reminders { 'lessonReminders' : Array<LessonReminder> }
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TeacherSchedule { 'time' : bigint, 'availability' : boolean }
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'branch' : string,
  'name' : string,
  'email' : string,
  'rollNumber' : string,
  'profilePicture' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WithdrawalRequest {
  'id' : string,
  'status' : WithdrawalStatus,
  'userId' : Principal,
  'timestamp' : bigint,
  'phoneNumber' : string,
  'amount' : number,
}
export type WithdrawalStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'authenticateAdmin' : ActorMethod<[string], boolean>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createLesson' : ActorMethod<[Lesson], string>,
  'deleteLesson' : ActorMethod<[string], undefined>,
  'getAllLessons' : ActorMethod<[], Array<Lesson>>,
  'getAllWithdrawalRequests' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLesson' : ActorMethod<[string], Lesson>,
  'getLessonStatus' : ActorMethod<[string], LessonStatus>,
  'getLessonTimeSpent' : ActorMethod<[string], bigint>,
  'getPhoneNumber' : ActorMethod<[], string>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWithdrawalRequest' : ActorMethod<[string], [] | [WithdrawalRequest]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPasswordSet' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveAdminPassword' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitWithdrawalRequest' : ActorMethod<[number, string], string>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateLesson' : ActorMethod<[string, Lesson], undefined>,
  'updateLessonStatus' : ActorMethod<[LessonStatusUpdate], undefined>,
  'updateWithdrawalStatus' : ActorMethod<[string, WithdrawalStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];