/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const FileType = IDL.Variant({
  'mp4' : IDL.Null,
  'pdf' : IDL.Null,
  'clarifiedPdf' : IDL.Null,
  'jpeg' : IDL.Null,
  'answeredQueries' : IDL.Null,
  'shortVideo' : IDL.Null,
  'notes' : IDL.Null,
  'longVideo' : IDL.Null,
  'mp3Audio' : IDL.Null,
  'pdfEncrypted' : IDL.Null,
  'zoomChart' : IDL.Null,
  'screenshot' : IDL.Null,
  'pdfWithQRCode' : IDL.Null,
});
export const File = IDL.Record({
  'id' : IDL.Text,
  'isEncrypted' : IDL.Bool,
  'fileLink' : IDL.Opt(IDL.Text),
  'fileType' : FileType,
});
export const UploadedFiles = IDL.Record({ 'files' : IDL.Vec(File) });
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const LessonReminder = IDL.Record({
  'interval' : IDL.Int,
  'text' : IDL.Text,
  'isActive' : IDL.Bool,
});
export const Reminders = IDL.Record({
  'lessonReminders' : IDL.Vec(LessonReminder),
});
export const TeacherSchedule = IDL.Record({
  'time' : IDL.Int,
  'availability' : IDL.Bool,
});
export const Lesson = IDL.Record({
  'id' : IDL.Text,
  'files' : IDL.Vec(File),
  'startTime' : IDL.Int,
  'title' : IDL.Text,
  'endTime' : IDL.Int,
  'description' : IDL.Text,
  'teacherName' : IDL.Text,
  'videoLink' : IDL.Opt(IDL.Text),
  'periodicReminders' : Reminders,
  'rating' : IDL.Float64,
  'ratingsCount' : IDL.Nat,
  'teacherSchedule' : IDL.Vec(TeacherSchedule),
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'refunded' : IDL.Null,
  'failed' : IDL.Null,
});
export const PaymentRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : PaymentStatus,
  'userId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'stripeSessionId' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
});
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const WithdrawalRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : WithdrawalStatus,
  'userId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'phoneNumber' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'branch' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'rollNumber' : IDL.Text,
  'profilePicture' : IDL.Opt(IDL.Text),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GalleryVideo = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
  'fileName' : IDL.Text,
});
export const GalleryImage = IDL.Record({
  'id' : IDL.Text,
  'blob' : IDL.Vec(IDL.Nat8),
  'fileName' : IDL.Text,
});
export const Gallery = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'branch' : IDL.Opt(IDL.Text),
  'semester' : IDL.Opt(IDL.Text),
  'subject' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'chapter' : IDL.Opt(IDL.Text),
  'videos' : IDL.Vec(GalleryVideo),
  'images' : IDL.Vec(GalleryImage),
});
export const LessonStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'started' : IDL.Null,
  'completed' : IDL.Null,
  'paused' : IDL.Null,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const LessonStatusUpdate = IDL.Record({
  'lessonId' : IDL.Text,
  'newStatus' : LessonStatus,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateUserAccount' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'authenticateAdmin' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'bulkDeleteCategories' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'bulkUpload' : IDL.Func([UploadedFiles], [], []),
  'checkForDuplicates' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'checkSubscriptionStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createGallery' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Text],
      [],
    ),
  'createLesson' : IDL.Func([Lesson], [IDL.Text], []),
  'deactivateUserAccount' : IDL.Func([IDL.Principal], [], []),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'deleteFile' : IDL.Func([IDL.Text], [], []),
  'deleteGallery' : IDL.Func([IDL.Text], [], []),
  'deleteGalleryImage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteGalleryVideo' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteImportantLink' : IDL.Func([IDL.Text], [], []),
  'deleteLesson' : IDL.Func([IDL.Text], [], []),
  'deleteVideoLink' : IDL.Func([IDL.Text], [], []),
  'finalizeStripeCheckout' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getActiveSubscriptions' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAllActiveSubscriptions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getAllLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getAllWithdrawalRequests' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getBankAccountDetails' : IDL.Func([], [IDL.Text, IDL.Text], ['query']),
  'getCallerPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFinalizedPurchases' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getGalleriesByCategory' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Vec(Gallery)],
      ['query'],
    ),
  'getGalleryById' : IDL.Func([IDL.Text], [IDL.Opt(Gallery)], ['query']),
  'getGalleryVideos' : IDL.Func([IDL.Text], [IDL.Vec(GalleryVideo)], ['query']),
  'getLesson' : IDL.Func([IDL.Text], [Lesson], ['query']),
  'getLessonStatus' : IDL.Func([IDL.Text], [LessonStatus], ['query']),
  'getLessonTimeSpent' : IDL.Func([IDL.Text], [IDL.Int], ['query']),
  'getPaymentById' : IDL.Func([IDL.Text], [IDL.Opt(PaymentRecord)], ['query']),
  'getPendingPurchases' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getPhonePePaymentsUPI' : IDL.Func([], [IDL.Text], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserPayments' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(PaymentRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWithdrawalRequest' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(WithdrawalRequest)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isPasswordSet' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isSubscriptionActive' : IDL.Func([], [IDL.Bool], ['query']),
  'saveAdminPassword' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitWithdrawalRequest' : IDL.Func([IDL.Float64, IDL.Text], [IDL.Text], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateLesson' : IDL.Func([IDL.Text, Lesson], [], []),
  'updateLessonStatus' : IDL.Func([LessonStatusUpdate], [], []),
  'updatePaymentStatus' : IDL.Func([IDL.Text, PaymentStatus], [], []),
  'updateWithdrawalStatus' : IDL.Func([IDL.Text, WithdrawalStatus], [], []),
  'uploadGalleryImages' : IDL.Func([IDL.Text, IDL.Vec(GalleryImage)], [], []),
  'uploadGalleryVideos' : IDL.Func([IDL.Text, IDL.Vec(GalleryVideo)], [], []),
  'validateFileSize' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const FileType = IDL.Variant({
    'mp4' : IDL.Null,
    'pdf' : IDL.Null,
    'clarifiedPdf' : IDL.Null,
    'jpeg' : IDL.Null,
    'answeredQueries' : IDL.Null,
    'shortVideo' : IDL.Null,
    'notes' : IDL.Null,
    'longVideo' : IDL.Null,
    'mp3Audio' : IDL.Null,
    'pdfEncrypted' : IDL.Null,
    'zoomChart' : IDL.Null,
    'screenshot' : IDL.Null,
    'pdfWithQRCode' : IDL.Null,
  });
  const File = IDL.Record({
    'id' : IDL.Text,
    'isEncrypted' : IDL.Bool,
    'fileLink' : IDL.Opt(IDL.Text),
    'fileType' : FileType,
  });
  const UploadedFiles = IDL.Record({ 'files' : IDL.Vec(File) });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const LessonReminder = IDL.Record({
    'interval' : IDL.Int,
    'text' : IDL.Text,
    'isActive' : IDL.Bool,
  });
  const Reminders = IDL.Record({ 'lessonReminders' : IDL.Vec(LessonReminder) });
  const TeacherSchedule = IDL.Record({
    'time' : IDL.Int,
    'availability' : IDL.Bool,
  });
  const Lesson = IDL.Record({
    'id' : IDL.Text,
    'files' : IDL.Vec(File),
    'startTime' : IDL.Int,
    'title' : IDL.Text,
    'endTime' : IDL.Int,
    'description' : IDL.Text,
    'teacherName' : IDL.Text,
    'videoLink' : IDL.Opt(IDL.Text),
    'periodicReminders' : Reminders,
    'rating' : IDL.Float64,
    'ratingsCount' : IDL.Nat,
    'teacherSchedule' : IDL.Vec(TeacherSchedule),
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'refunded' : IDL.Null,
    'failed' : IDL.Null,
  });
  const PaymentRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : PaymentStatus,
    'userId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'stripeSessionId' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
  });
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const WithdrawalRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : WithdrawalStatus,
    'userId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'phoneNumber' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({
    'branch' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'rollNumber' : IDL.Text,
    'profilePicture' : IDL.Opt(IDL.Text),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GalleryVideo = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
    'fileName' : IDL.Text,
  });
  const GalleryImage = IDL.Record({
    'id' : IDL.Text,
    'blob' : IDL.Vec(IDL.Nat8),
    'fileName' : IDL.Text,
  });
  const Gallery = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'branch' : IDL.Opt(IDL.Text),
    'semester' : IDL.Opt(IDL.Text),
    'subject' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'chapter' : IDL.Opt(IDL.Text),
    'videos' : IDL.Vec(GalleryVideo),
    'images' : IDL.Vec(GalleryImage),
  });
  const LessonStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'started' : IDL.Null,
    'completed' : IDL.Null,
    'paused' : IDL.Null,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const LessonStatusUpdate = IDL.Record({
    'lessonId' : IDL.Text,
    'newStatus' : LessonStatus,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateUserAccount' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'authenticateAdmin' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'bulkDeleteCategories' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'bulkUpload' : IDL.Func([UploadedFiles], [], []),
    'checkForDuplicates' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'checkSubscriptionStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createGallery' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Text],
        [],
      ),
    'createLesson' : IDL.Func([Lesson], [IDL.Text], []),
    'deactivateUserAccount' : IDL.Func([IDL.Principal], [], []),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'deleteFile' : IDL.Func([IDL.Text], [], []),
    'deleteGallery' : IDL.Func([IDL.Text], [], []),
    'deleteGalleryImage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteGalleryVideo' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteImportantLink' : IDL.Func([IDL.Text], [], []),
    'deleteLesson' : IDL.Func([IDL.Text], [], []),
    'deleteVideoLink' : IDL.Func([IDL.Text], [], []),
    'finalizeStripeCheckout' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getActiveSubscriptions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getAllActiveSubscriptions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getAllLessons' : IDL.Func([], [IDL.Vec(Lesson)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getAllWithdrawalRequests' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getBankAccountDetails' : IDL.Func([], [IDL.Text, IDL.Text], ['query']),
    'getCallerPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFinalizedPurchases' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getGalleriesByCategory' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Vec(Gallery)],
        ['query'],
      ),
    'getGalleryById' : IDL.Func([IDL.Text], [IDL.Opt(Gallery)], ['query']),
    'getGalleryVideos' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GalleryVideo)],
        ['query'],
      ),
    'getLesson' : IDL.Func([IDL.Text], [Lesson], ['query']),
    'getLessonStatus' : IDL.Func([IDL.Text], [LessonStatus], ['query']),
    'getLessonTimeSpent' : IDL.Func([IDL.Text], [IDL.Int], ['query']),
    'getPaymentById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PaymentRecord)],
        ['query'],
      ),
    'getPendingPurchases' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getPhonePePaymentsUPI' : IDL.Func([], [IDL.Text], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserPayments' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(PaymentRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWithdrawalRequest' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(WithdrawalRequest)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isPasswordSet' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isSubscriptionActive' : IDL.Func([], [IDL.Bool], ['query']),
    'saveAdminPassword' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitWithdrawalRequest' : IDL.Func(
        [IDL.Float64, IDL.Text],
        [IDL.Text],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateLesson' : IDL.Func([IDL.Text, Lesson], [], []),
    'updateLessonStatus' : IDL.Func([LessonStatusUpdate], [], []),
    'updatePaymentStatus' : IDL.Func([IDL.Text, PaymentStatus], [], []),
    'updateWithdrawalStatus' : IDL.Func([IDL.Text, WithdrawalStatus], [], []),
    'uploadGalleryImages' : IDL.Func([IDL.Text, IDL.Vec(GalleryImage)], [], []),
    'uploadGalleryVideos' : IDL.Func([IDL.Text, IDL.Vec(GalleryVideo)], [], []),
    'validateFileSize' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };