/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface PaymentRecord {
    id: string;
    status: PaymentStatus;
    userId: Principal;
    timestamp: bigint;
    stripeSessionId?: string;
    amount: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Lesson {
    id: string;
    files: Array<File>;
    startTime: bigint;
    title: string;
    endTime: bigint;
    description: string;
    teacherName: string;
    videoLink?: string;
    periodicReminders: Reminders;
    rating: number;
    ratingsCount: bigint;
    teacherSchedule: Array<TeacherSchedule>;
}
export interface GalleryImage {
    id: string;
    blob: Uint8Array;
    fileName: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface Gallery {
    id: string;
    title: string;
    branch?: string;
    semester?: string;
    subject?: string;
    description: string;
    chapter?: string;
    videos: Array<GalleryVideo>;
    images: Array<GalleryImage>;
}
export interface GalleryVideo {
    id: string;
    blob: ExternalBlob;
    fileName: string;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface LessonStatusUpdate {
    lessonId: string;
    newStatus: LessonStatus;
}
export interface File {
    id: string;
    isEncrypted: boolean;
    fileLink?: string;
    fileType: FileType;
}
export interface UploadedFiles {
    files: Array<File>;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TeacherSchedule {
    time: bigint;
    availability: boolean;
}
export interface Reminders {
    lessonReminders: Array<LessonReminder>;
}
export interface LessonReminder {
    interval: bigint;
    text: string;
    isActive: boolean;
}
export interface WithdrawalRequest {
    id: string;
    status: WithdrawalStatus;
    userId: Principal;
    timestamp: bigint;
    phoneNumber: string;
    amount: number;
}
export interface UserProfile {
    branch: string;
    name: string;
    email: string;
    rollNumber: string;
    profilePicture?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum FileType {
    mp4 = "mp4",
    pdf = "pdf",
    clarifiedPdf = "clarifiedPdf",
    jpeg = "jpeg",
    answeredQueries = "answeredQueries",
    shortVideo = "shortVideo",
    notes = "notes",
    longVideo = "longVideo",
    mp3Audio = "mp3Audio",
    pdfEncrypted = "pdfEncrypted",
    zoomChart = "zoomChart",
    screenshot = "screenshot",
    pdfWithQRCode = "pdfWithQRCode"
}
export enum LessonStatus {
    notStarted = "notStarted",
    started = "started",
    completed = "completed",
    paused = "paused"
}
export enum PaymentStatus {
    pending = "pending",
    completed = "completed",
    refunded = "refunded",
    failed = "failed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WithdrawalStatus {
    pending = "pending",
    completed = "completed",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    activateUserAccount(userId: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    authenticateAdmin(_incomingPassword: string): Promise<boolean>;
    bulkDeleteCategories(_categoryIds: Array<string>): Promise<void>;
    bulkUpload(_data: UploadedFiles): Promise<void>;
    checkForDuplicates(_fileName: string, _category: string): Promise<boolean>;
    checkSubscriptionStatus(): Promise<boolean>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createGallery(title: string, description: string, branch: string | null, semester: string | null, subject: string | null, chapter: string | null): Promise<string>;
    createLesson(lesson: Lesson): Promise<string>;
    deactivateUserAccount(userId: Principal): Promise<void>;
    deleteCategory(_categoryId: string): Promise<void>;
    deleteFile(_fileId: string): Promise<void>;
    deleteGallery(galleryId: string): Promise<void>;
    deleteGalleryImage(galleryId: string, imageId: string): Promise<void>;
    deleteGalleryVideo(galleryId: string, videoId: string): Promise<void>;
    deleteImportantLink(_linkId: string): Promise<void>;
    deleteLesson(lessonId: string): Promise<void>;
    deleteVideoLink(_linkId: string): Promise<void>;
    finalizeStripeCheckout(sessionId: string): Promise<boolean>;
    getActiveSubscriptions(): Promise<Array<Principal>>;
    getAllActiveSubscriptions(): Promise<Array<Principal>>;
    getAllLessons(): Promise<Array<Lesson>>;
    getAllPayments(): Promise<Array<PaymentRecord>>;
    getAllWithdrawalRequests(): Promise<Array<WithdrawalRequest>>;
    getBankAccountDetails(): Promise<[string, string]>;
    getCallerPayments(): Promise<Array<PaymentRecord>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFinalizedPurchases(): Promise<Array<string>>;
    getGalleriesByCategory(_branch: string | null, _semester: string | null, _subject: string | null, _chapter: string | null): Promise<Array<Gallery>>;
    getGalleryById(galleryId: string): Promise<Gallery | null>;
    getGalleryVideos(galleryId: string): Promise<Array<GalleryVideo>>;
    getLesson(lessonId: string): Promise<Lesson>;
    getLessonStatus(lessonId: string): Promise<LessonStatus>;
    getLessonTimeSpent(lessonId: string): Promise<bigint>;
    getPaymentById(paymentId: string): Promise<PaymentRecord | null>;
    getPendingPurchases(): Promise<Array<string>>;
    getPhonePePaymentsUPI(): Promise<string>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserPayments(userId: Principal): Promise<Array<PaymentRecord>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWithdrawalRequest(withdrawalId: string): Promise<WithdrawalRequest | null>;
    isCallerAdmin(): Promise<boolean>;
    isPasswordSet(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    isSubscriptionActive(): Promise<boolean>;
    saveAdminPassword(_password: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    submitWithdrawalRequest(amount: number, phoneNumber: string): Promise<string>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateLesson(lessonId: string, updatedLesson: Lesson): Promise<void>;
    updateLessonStatus(update: LessonStatusUpdate): Promise<void>;
    updatePaymentStatus(paymentId: string, newStatus: PaymentStatus): Promise<void>;
    updateWithdrawalStatus(withdrawalId: string, newStatus: WithdrawalStatus): Promise<void>;
    uploadGalleryImages(galleryId: string, images: Array<GalleryImage>): Promise<void>;
    uploadGalleryVideos(galleryId: string, videos: Array<GalleryVideo>): Promise<void>;
    validateFileSize(_fileSize: bigint): Promise<boolean>;
}
import type { ExternalBlob as _ExternalBlob, File as _File, FileType as _FileType, Gallery as _Gallery, GalleryImage as _GalleryImage, GalleryVideo as _GalleryVideo, Lesson as _Lesson, LessonStatus as _LessonStatus, LessonStatusUpdate as _LessonStatusUpdate, PaymentRecord as _PaymentRecord, PaymentStatus as _PaymentStatus, Reminders as _Reminders, StripeSessionStatus as _StripeSessionStatus, TeacherSchedule as _TeacherSchedule, UploadedFiles as _UploadedFiles, UserProfile as _UserProfile, UserRole as _UserRole, WithdrawalRequest as _WithdrawalRequest, WithdrawalStatus as _WithdrawalStatus, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async activateUserAccount(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activateUserAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateUserAccount(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async authenticateAdmin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.authenticateAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.authenticateAdmin(arg0);
            return result;
        }
    }
    async bulkDeleteCategories(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkDeleteCategories(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkDeleteCategories(arg0);
            return result;
        }
    }
    async bulkUpload(arg0: UploadedFiles): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkUpload(to_candid_UploadedFiles_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkUpload(to_candid_UploadedFiles_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async checkForDuplicates(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkForDuplicates(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkForDuplicates(arg0, arg1);
            return result;
        }
    }
    async checkSubscriptionStatus(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkSubscriptionStatus();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkSubscriptionStatus();
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createGallery(arg0: string, arg1: string, arg2: string | null, arg3: string | null, arg4: string | null, arg5: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createGallery(arg0, arg1, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGallery(arg0, arg1, to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async createLesson(arg0: Lesson): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createLesson(to_candid_Lesson_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLesson(to_candid_Lesson_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deactivateUserAccount(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateUserAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateUserAccount(arg0);
            return result;
        }
    }
    async deleteCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteFile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFile(arg0);
            return result;
        }
    }
    async deleteGallery(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGallery(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGallery(arg0);
            return result;
        }
    }
    async deleteGalleryImage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryImage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryImage(arg0, arg1);
            return result;
        }
    }
    async deleteGalleryVideo(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryVideo(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryVideo(arg0, arg1);
            return result;
        }
    }
    async deleteImportantLink(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteImportantLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteImportantLink(arg0);
            return result;
        }
    }
    async deleteLesson(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLesson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLesson(arg0);
            return result;
        }
    }
    async deleteVideoLink(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideoLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideoLink(arg0);
            return result;
        }
    }
    async finalizeStripeCheckout(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.finalizeStripeCheckout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finalizeStripeCheckout(arg0);
            return result;
        }
    }
    async getActiveSubscriptions(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveSubscriptions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveSubscriptions();
            return result;
        }
    }
    async getAllActiveSubscriptions(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActiveSubscriptions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActiveSubscriptions();
            return result;
        }
    }
    async getAllLessons(): Promise<Array<Lesson>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLessons();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllLessons();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPayments(): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayments();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayments();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWithdrawalRequests(): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWithdrawalRequests();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWithdrawalRequests();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBankAccountDetails(): Promise<[string, string]> {
        if (this.processError) {
            try {
                const result = await this.actor.getBankAccountDetails();
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBankAccountDetails();
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getCallerPayments(): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPayments();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPayments();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFinalizedPurchases(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFinalizedPurchases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFinalizedPurchases();
            return result;
        }
    }
    async getGalleriesByCategory(arg0: string | null, arg1: string | null, arg2: string | null, arg3: string | null): Promise<Array<Gallery>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleriesByCategory(to_candid_opt_n17(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg3));
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleriesByCategory(to_candid_opt_n17(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg3));
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGalleryById(arg0: string): Promise<Gallery | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryById(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryById(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGalleryVideos(arg0: string): Promise<Array<GalleryVideo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryVideos(arg0);
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryVideos(arg0);
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLesson(arg0: string): Promise<Lesson> {
        if (this.processError) {
            try {
                const result = await this.actor.getLesson(arg0);
                return from_candid_Lesson_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLesson(arg0);
            return from_candid_Lesson_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLessonStatus(arg0: string): Promise<LessonStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessonStatus(arg0);
                return from_candid_LessonStatus_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessonStatus(arg0);
            return from_candid_LessonStatus_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLessonTimeSpent(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getLessonTimeSpent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLessonTimeSpent(arg0);
            return result;
        }
    }
    async getPaymentById(arg0: string): Promise<PaymentRecord | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentById(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentById(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingPurchases(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingPurchases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingPurchases();
            return result;
        }
    }
    async getPhonePePaymentsUPI(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getPhonePePaymentsUPI();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPhonePePaymentsUPI();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPayments(arg0: Principal): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPayments(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPayments(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWithdrawalRequest(arg0: string): Promise<WithdrawalRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWithdrawalRequest(arg0);
                return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWithdrawalRequest(arg0);
            return from_candid_opt_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isPasswordSet(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isPasswordSet();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isPasswordSet();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async isSubscriptionActive(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isSubscriptionActive();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isSubscriptionActive();
            return result;
        }
    }
    async saveAdminPassword(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveAdminPassword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveAdminPassword(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n59(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n59(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async submitWithdrawalRequest(arg0: number, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.submitWithdrawalRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitWithdrawalRequest(arg0, arg1);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateLesson(arg0: string, arg1: Lesson): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLesson(arg0, to_candid_Lesson_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLesson(arg0, to_candid_Lesson_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateLessonStatus(arg0: LessonStatusUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLessonStatus(to_candid_LessonStatusUpdate_n61(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLessonStatus(to_candid_LessonStatusUpdate_n61(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updatePaymentStatus(arg0: string, arg1: PaymentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n65(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n65(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateWithdrawalStatus(arg0: string, arg1: WithdrawalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWithdrawalStatus(arg0, to_candid_WithdrawalStatus_n67(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWithdrawalStatus(arg0, to_candid_WithdrawalStatus_n67(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async uploadGalleryImages(arg0: string, arg1: Array<GalleryImage>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadGalleryImages(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadGalleryImages(arg0, arg1);
            return result;
        }
    }
    async uploadGalleryVideos(arg0: string, arg1: Array<GalleryVideo>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadGalleryVideos(arg0, await to_candid_vec_n69(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadGalleryVideos(arg0, await to_candid_vec_n69(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async validateFileSize(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateFileSize(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateFileSize(arg0);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FileType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileType): FileType {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_File_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _File): File {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_GalleryVideo_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryVideo): Promise<GalleryVideo> {
    return await from_candid_record_n49(_uploadFile, _downloadFile, value);
}
async function from_candid_Gallery_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gallery): Promise<Gallery> {
    return await from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_LessonStatus_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LessonStatus): LessonStatus {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_Lesson_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lesson): Lesson {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentRecord_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentRecord): PaymentRecord {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalRequest_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalRequest): WithdrawalRequest {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalStatus): WithdrawalStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n40(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Gallery]): Promise<Gallery | null> {
    return value.length === 0 ? null : await from_candid_Gallery_n45(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentRecord]): PaymentRecord | null {
    return value.length === 0 ? null : from_candid_PaymentRecord_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WithdrawalRequest]): WithdrawalRequest | null {
    return value.length === 0 ? null : from_candid_WithdrawalRequest_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    files: Array<_File>;
    startTime: bigint;
    title: string;
    endTime: bigint;
    description: string;
    teacherName: string;
    videoLink: [] | [string];
    periodicReminders: _Reminders;
    rating: number;
    ratingsCount: bigint;
    teacherSchedule: Array<_TeacherSchedule>;
}): {
    id: string;
    files: Array<File>;
    startTime: bigint;
    title: string;
    endTime: bigint;
    description: string;
    teacherName: string;
    videoLink?: string;
    periodicReminders: Reminders;
    rating: number;
    ratingsCount: bigint;
    teacherSchedule: Array<TeacherSchedule>;
} {
    return {
        id: value.id,
        files: from_candid_vec_n23(_uploadFile, _downloadFile, value.files),
        startTime: value.startTime,
        title: value.title,
        endTime: value.endTime,
        description: value.description,
        teacherName: value.teacherName,
        videoLink: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.videoLink)),
        periodicReminders: value.periodicReminders,
        rating: value.rating,
        ratingsCount: value.ratingsCount,
        teacherSchedule: value.teacherSchedule
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    isEncrypted: boolean;
    fileLink: [] | [string];
    fileType: _FileType;
}): {
    id: string;
    isEncrypted: boolean;
    fileLink?: string;
    fileType: FileType;
} {
    return {
        id: value.id,
        isEncrypted: value.isEncrypted,
        fileLink: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.fileLink)),
        fileType: from_candid_FileType_n27(_uploadFile, _downloadFile, value.fileType)
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _PaymentStatus;
    userId: Principal;
    timestamp: bigint;
    stripeSessionId: [] | [string];
    amount: bigint;
}): {
    id: string;
    status: PaymentStatus;
    userId: Principal;
    timestamp: bigint;
    stripeSessionId?: string;
    amount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_PaymentStatus_n32(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        timestamp: value.timestamp,
        stripeSessionId: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.stripeSessionId)),
        amount: value.amount
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _WithdrawalStatus;
    userId: Principal;
    timestamp: bigint;
    phoneNumber: string;
    amount: number;
}): {
    id: string;
    status: WithdrawalStatus;
    userId: Principal;
    timestamp: bigint;
    phoneNumber: string;
    amount: number;
} {
    return {
        id: value.id,
        status: from_candid_WithdrawalStatus_n37(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        timestamp: value.timestamp,
        phoneNumber: value.phoneNumber,
        amount: value.amount
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    branch: string;
    name: string;
    email: string;
    rollNumber: string;
    profilePicture: [] | [string];
}): {
    branch: string;
    name: string;
    email: string;
    rollNumber: string;
    profilePicture?: string;
} {
    return {
        branch: value.branch,
        name: value.name,
        email: value.email,
        rollNumber: value.rollNumber,
        profilePicture: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.profilePicture))
    };
}
async function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    branch: [] | [string];
    semester: [] | [string];
    subject: [] | [string];
    description: string;
    chapter: [] | [string];
    videos: Array<_GalleryVideo>;
    images: Array<_GalleryImage>;
}): Promise<{
    id: string;
    title: string;
    branch?: string;
    semester?: string;
    subject?: string;
    description: string;
    chapter?: string;
    videos: Array<GalleryVideo>;
    images: Array<GalleryImage>;
}> {
    return {
        id: value.id,
        title: value.title,
        branch: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.branch)),
        semester: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.semester)),
        subject: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.subject)),
        description: value.description,
        chapter: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.chapter)),
        videos: await from_candid_vec_n47(_uploadFile, _downloadFile, value.videos),
        images: value.images
    };
}
async function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    blob: _ExternalBlob;
    fileName: string;
}): Promise<{
    id: string;
    blob: ExternalBlob;
    fileName: string;
}> {
    return {
        id: value.id,
        blob: await from_candid_ExternalBlob_n50(_uploadFile, _downloadFile, value.blob),
        fileName: value.fileName
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mp4: null;
} | {
    pdf: null;
} | {
    clarifiedPdf: null;
} | {
    jpeg: null;
} | {
    answeredQueries: null;
} | {
    shortVideo: null;
} | {
    notes: null;
} | {
    longVideo: null;
} | {
    mp3Audio: null;
} | {
    pdfEncrypted: null;
} | {
    zoomChart: null;
} | {
    screenshot: null;
} | {
    pdfWithQRCode: null;
}): FileType {
    return "mp4" in value ? FileType.mp4 : "pdf" in value ? FileType.pdf : "clarifiedPdf" in value ? FileType.clarifiedPdf : "jpeg" in value ? FileType.jpeg : "answeredQueries" in value ? FileType.answeredQueries : "shortVideo" in value ? FileType.shortVideo : "notes" in value ? FileType.notes : "longVideo" in value ? FileType.longVideo : "mp3Audio" in value ? FileType.mp3Audio : "pdfEncrypted" in value ? FileType.pdfEncrypted : "zoomChart" in value ? FileType.zoomChart : "screenshot" in value ? FileType.screenshot : "pdfWithQRCode" in value ? FileType.pdfWithQRCode : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    refunded: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "completed" in value ? PaymentStatus.completed : "refunded" in value ? PaymentStatus.refunded : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    approved: null;
} | {
    rejected: null;
}): WithdrawalStatus {
    return "pending" in value ? WithdrawalStatus.pending : "completed" in value ? WithdrawalStatus.completed : "approved" in value ? WithdrawalStatus.approved : "rejected" in value ? WithdrawalStatus.rejected : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notStarted: null;
} | {
    started: null;
} | {
    completed: null;
} | {
    paused: null;
}): LessonStatus {
    return "notStarted" in value ? LessonStatus.notStarted : "started" in value ? LessonStatus.started : "completed" in value ? LessonStatus.completed : "paused" in value ? LessonStatus.paused : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n57(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lesson>): Array<Lesson> {
    return value.map((x)=>from_candid_Lesson_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_File>): Array<File> {
    return value.map((x)=>from_candid_File_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentRecord>): Array<PaymentRecord> {
    return value.map((x)=>from_candid_PaymentRecord_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawalRequest>): Array<WithdrawalRequest> {
    return value.map((x)=>from_candid_WithdrawalRequest_n35(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Gallery>): Promise<Array<Gallery>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Gallery_n45(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryVideo>): Promise<Array<GalleryVideo>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GalleryVideo_n48(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FileType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileType): _FileType {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_File_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: File): _File {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
async function to_candid_GalleryVideo_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GalleryVideo): Promise<_GalleryVideo> {
    return await to_candid_record_n71(_uploadFile, _downloadFile, value);
}
function to_candid_LessonStatusUpdate_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LessonStatusUpdate): _LessonStatusUpdate {
    return to_candid_record_n62(_uploadFile, _downloadFile, value);
}
function to_candid_LessonStatus_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LessonStatus): _LessonStatus {
    return to_candid_variant_n64(_uploadFile, _downloadFile, value);
}
function to_candid_Lesson_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Lesson): _Lesson {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function to_candid_UploadedFiles_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UploadedFiles): _UploadedFiles {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_WithdrawalStatus_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WithdrawalStatus): _WithdrawalStatus {
    return to_candid_variant_n68(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    files: Array<File>;
}): {
    files: Array<_File>;
} {
    return {
        files: to_candid_vec_n12(_uploadFile, _downloadFile, value.files)
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    isEncrypted: boolean;
    fileLink?: string;
    fileType: FileType;
}): {
    id: string;
    isEncrypted: boolean;
    fileLink: [] | [string];
    fileType: _FileType;
} {
    return {
        id: value.id,
        isEncrypted: value.isEncrypted,
        fileLink: value.fileLink ? candid_some(value.fileLink) : candid_none(),
        fileType: to_candid_FileType_n15(_uploadFile, _downloadFile, value.fileType)
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    files: Array<File>;
    startTime: bigint;
    title: string;
    endTime: bigint;
    description: string;
    teacherName: string;
    videoLink?: string;
    periodicReminders: Reminders;
    rating: number;
    ratingsCount: bigint;
    teacherSchedule: Array<TeacherSchedule>;
}): {
    id: string;
    files: Array<_File>;
    startTime: bigint;
    title: string;
    endTime: bigint;
    description: string;
    teacherName: string;
    videoLink: [] | [string];
    periodicReminders: _Reminders;
    rating: number;
    ratingsCount: bigint;
    teacherSchedule: Array<_TeacherSchedule>;
} {
    return {
        id: value.id,
        files: to_candid_vec_n12(_uploadFile, _downloadFile, value.files),
        startTime: value.startTime,
        title: value.title,
        endTime: value.endTime,
        description: value.description,
        teacherName: value.teacherName,
        videoLink: value.videoLink ? candid_some(value.videoLink) : candid_none(),
        periodicReminders: value.periodicReminders,
        rating: value.rating,
        ratingsCount: value.ratingsCount,
        teacherSchedule: value.teacherSchedule
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    branch: string;
    name: string;
    email: string;
    rollNumber: string;
    profilePicture?: string;
}): {
    branch: string;
    name: string;
    email: string;
    rollNumber: string;
    profilePicture: [] | [string];
} {
    return {
        branch: value.branch,
        name: value.name,
        email: value.email,
        rollNumber: value.rollNumber,
        profilePicture: value.profilePicture ? candid_some(value.profilePicture) : candid_none()
    };
}
function to_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lessonId: string;
    newStatus: LessonStatus;
}): {
    lessonId: string;
    newStatus: _LessonStatus;
} {
    return {
        lessonId: value.lessonId,
        newStatus: to_candid_LessonStatus_n63(_uploadFile, _downloadFile, value.newStatus)
    };
}
async function to_candid_record_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    blob: ExternalBlob;
    fileName: string;
}): Promise<{
    id: string;
    blob: _ExternalBlob;
    fileName: string;
}> {
    return {
        id: value.id,
        blob: await to_candid_ExternalBlob_n72(_uploadFile, _downloadFile, value.blob),
        fileName: value.fileName
    };
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileType): {
    mp4: null;
} | {
    pdf: null;
} | {
    clarifiedPdf: null;
} | {
    jpeg: null;
} | {
    answeredQueries: null;
} | {
    shortVideo: null;
} | {
    notes: null;
} | {
    longVideo: null;
} | {
    mp3Audio: null;
} | {
    pdfEncrypted: null;
} | {
    zoomChart: null;
} | {
    screenshot: null;
} | {
    pdfWithQRCode: null;
} {
    return value == FileType.mp4 ? {
        mp4: null
    } : value == FileType.pdf ? {
        pdf: null
    } : value == FileType.clarifiedPdf ? {
        clarifiedPdf: null
    } : value == FileType.jpeg ? {
        jpeg: null
    } : value == FileType.answeredQueries ? {
        answeredQueries: null
    } : value == FileType.shortVideo ? {
        shortVideo: null
    } : value == FileType.notes ? {
        notes: null
    } : value == FileType.longVideo ? {
        longVideo: null
    } : value == FileType.mp3Audio ? {
        mp3Audio: null
    } : value == FileType.pdfEncrypted ? {
        pdfEncrypted: null
    } : value == FileType.zoomChart ? {
        zoomChart: null
    } : value == FileType.screenshot ? {
        screenshot: null
    } : value == FileType.pdfWithQRCode ? {
        pdfWithQRCode: null
    } : value;
}
function to_candid_variant_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LessonStatus): {
    notStarted: null;
} | {
    started: null;
} | {
    completed: null;
} | {
    paused: null;
} {
    return value == LessonStatus.notStarted ? {
        notStarted: null
    } : value == LessonStatus.started ? {
        started: null
    } : value == LessonStatus.completed ? {
        completed: null
    } : value == LessonStatus.paused ? {
        paused: null
    } : value;
}
function to_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    pending: null;
} | {
    completed: null;
} | {
    refunded: null;
} | {
    failed: null;
} {
    return value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.completed ? {
        completed: null
    } : value == PaymentStatus.refunded ? {
        refunded: null
    } : value == PaymentStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WithdrawalStatus): {
    pending: null;
} | {
    completed: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == WithdrawalStatus.pending ? {
        pending: null
    } : value == WithdrawalStatus.completed ? {
        completed: null
    } : value == WithdrawalStatus.approved ? {
        approved: null
    } : value == WithdrawalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<File>): Array<_File> {
    return value.map((x)=>to_candid_File_n13(_uploadFile, _downloadFile, x));
}
async function to_candid_vec_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<GalleryVideo>): Promise<Array<_GalleryVideo>> {
    return await Promise.all(value.map(async (x)=>await to_candid_GalleryVideo_n70(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
